// <auto-generated />
using System;
using BloodPressure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodPressure.Persistence.Migrations
{
    [DbContext(typeof(BloodPressureDbContext))]
    [Migration("20260209133221_AddTimeSlotDefinitions")]
    partial class AddTimeSlotDefinitions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodPressure.Persistence.Entities.LicenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("EndDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("StartDateUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.ReadingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ColorKey")
                        .HasColumnType("int");

                    b.Property<int>("Diastolic")
                        .HasColumnType("int");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("int");

                    b.Property<bool>("MedicationSkipped")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int?>("SportActivityOptionId")
                        .HasColumnType("int");

                    b.Property<int>("Systolic")
                        .HasColumnType("int");

                    b.Property<int?>("TimeSlotOptionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("SportActivityOptionId");

                    b.HasIndex("TimeSlotOptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Readings");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.ReadingSymptomEntity", b =>
                {
                    b.Property<Guid>("ReadingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SymptomOptionId")
                        .HasColumnType("int");

                    b.HasKey("ReadingId", "SymptomOptionId");

                    b.HasIndex("SymptomOptionId");

                    b.ToTable("ReadingSymptoms");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.SportActivityOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SportActivityOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Light"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Moderate"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Intense"
                        });
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.SymptomOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SymptomOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Headache"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dizziness"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Nausea"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chest Pain"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Blurred Vision"
                        });
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.TimeSlotOptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TimeSlotOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mattino"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pomeriggio"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sera"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Notte"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mezzo giorno"
                        });
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.UserSettingsEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSlotDefinitions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.LicenseEntity", b =>
                {
                    b.HasOne("BloodPressure.Persistence.Entities.UserEntity", "User")
                        .WithMany("Licenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.ReadingEntity", b =>
                {
                    b.HasOne("BloodPressure.Persistence.Entities.SportActivityOptionEntity", "SportActivityOption")
                        .WithMany()
                        .HasForeignKey("SportActivityOptionId");

                    b.HasOne("BloodPressure.Persistence.Entities.TimeSlotOptionEntity", "TimeSlotOption")
                        .WithMany()
                        .HasForeignKey("TimeSlotOptionId");

                    b.HasOne("BloodPressure.Persistence.Entities.UserEntity", "User")
                        .WithMany("Readings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SportActivityOption");

                    b.Navigation("TimeSlotOption");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.ReadingSymptomEntity", b =>
                {
                    b.HasOne("BloodPressure.Persistence.Entities.ReadingEntity", "Reading")
                        .WithMany("Symptoms")
                        .HasForeignKey("ReadingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BloodPressure.Persistence.Entities.SymptomOptionEntity", "SymptomOption")
                        .WithMany("Readings")
                        .HasForeignKey("SymptomOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reading");

                    b.Navigation("SymptomOption");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.UserSettingsEntity", b =>
                {
                    b.HasOne("BloodPressure.Persistence.Entities.UserEntity", "User")
                        .WithOne("Settings")
                        .HasForeignKey("BloodPressure.Persistence.Entities.UserSettingsEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BloodPressure.Persistence.Entities.ClinicalThresholdsEntity", "Thresholds", b1 =>
                        {
                            b1.Property<Guid>("UserSettingsEntityUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("UserSettingsEntityUserId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsEntityUserId");

                            b1.OwnsOne("BloodPressure.Persistence.Entities.ThresholdSetEntity", "Diastolic", b2 =>
                                {
                                    b2.Property<Guid>("ClinicalThresholdsEntityUserSettingsEntityUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("HighMax")
                                        .HasColumnType("int")
                                        .HasColumnName("DiastolicHighMax");

                                    b2.Property<int>("LowMax")
                                        .HasColumnType("int")
                                        .HasColumnName("DiastolicLowMax");

                                    b2.Property<int>("NormalMax")
                                        .HasColumnType("int")
                                        .HasColumnName("DiastolicNormalMax");

                                    b2.Property<int>("VeryLowMax")
                                        .HasColumnType("int")
                                        .HasColumnName("DiastolicVeryLowMax");

                                    b2.HasKey("ClinicalThresholdsEntityUserSettingsEntityUserId");

                                    b2.ToTable("UserSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("ClinicalThresholdsEntityUserSettingsEntityUserId");
                                });

                            b1.OwnsOne("BloodPressure.Persistence.Entities.ThresholdSetEntity", "Systolic", b2 =>
                                {
                                    b2.Property<Guid>("ClinicalThresholdsEntityUserSettingsEntityUserId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("HighMax")
                                        .HasColumnType("int")
                                        .HasColumnName("SystolicHighMax");

                                    b2.Property<int>("LowMax")
                                        .HasColumnType("int")
                                        .HasColumnName("SystolicLowMax");

                                    b2.Property<int>("NormalMax")
                                        .HasColumnType("int")
                                        .HasColumnName("SystolicNormalMax");

                                    b2.Property<int>("VeryLowMax")
                                        .HasColumnType("int")
                                        .HasColumnName("SystolicVeryLowMax");

                                    b2.HasKey("ClinicalThresholdsEntityUserSettingsEntityUserId");

                                    b2.ToTable("UserSettings");

                                    b2.WithOwner()
                                        .HasForeignKey("ClinicalThresholdsEntityUserSettingsEntityUserId");
                                });

                            b1.Navigation("Diastolic")
                                .IsRequired();

                            b1.Navigation("Systolic")
                                .IsRequired();
                        });

                    b.OwnsOne("BloodPressure.Persistence.Entities.DashboardPreferencesEntity", "DashboardPreferences", b1 =>
                        {
                            b1.Property<Guid>("UserSettingsEntityUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("DefaultRangeDays")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasDefaultValue(30);

                            b1.HasKey("UserSettingsEntityUserId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsEntityUserId");
                        });

                    b.OwnsOne("BloodPressure.Persistence.Entities.DefaultSelectionsEntity", "DefaultSelections", b1 =>
                        {
                            b1.Property<Guid>("UserSettingsEntityUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("SportActivityOptionId")
                                .HasColumnType("int");

                            b1.Property<string>("SymptomOptionIds")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DefaultSymptomOptionIds");

                            b1.Property<int?>("TimeSlotOptionId")
                                .HasColumnType("int");

                            b1.HasKey("UserSettingsEntityUserId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsEntityUserId");
                        });

                    b.OwnsOne("BloodPressure.Persistence.Entities.UiPreferencesEntity", "UiPreferences", b1 =>
                        {
                            b1.Property<Guid>("UserSettingsEntityUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<bool>("CompactMode")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bit")
                                .HasDefaultValue(false);

                            b1.HasKey("UserSettingsEntityUserId");

                            b1.ToTable("UserSettings");

                            b1.WithOwner()
                                .HasForeignKey("UserSettingsEntityUserId");
                        });

                    b.Navigation("DashboardPreferences")
                        .IsRequired();

                    b.Navigation("DefaultSelections")
                        .IsRequired();

                    b.Navigation("Thresholds")
                        .IsRequired();

                    b.Navigation("UiPreferences")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.ReadingEntity", b =>
                {
                    b.Navigation("Symptoms");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.SymptomOptionEntity", b =>
                {
                    b.Navigation("Readings");
                });

            modelBuilder.Entity("BloodPressure.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Licenses");

                    b.Navigation("Readings");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
